name: Renovate Bot

on:
  push:
    branches:
      - "**"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Renovate Bot GitHub Action
        uses: renovatebot/github-action@v44.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
