name: EndSectors-Tools
version: 1.0
main: pl.endixon.sectors.tools.Main
api-version: 1.20
depend: [EndSectors]

commands:
  randomtp:
    description: Losowy teleport w sektorze
    usage: /randomtp
  spawn:
    description: Teleport na spawn
    usage: /spawn
  home:
    description: Teleport na swój home
    usage: /home
